[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.23"

[features]
resolution = true
skip-lint = false

[programs.localnet]
# zetachain_gateway_solana = "sNFcER7pcD5i6kMQXxd6ZdqxpF5hhYQv76VheZFzEi2"
gateway_send = "CbcR39gxjR2BH69ARzf5KF3tWSuNa9qpMaFSPecWgpNK"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
#wallet = "~/.config/solana/id.json"
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/test_id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
