[workspace]
members = [
  "programs/*",
  "client",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"
overflow-checks = true
[profile.release.build-override]
codegen-units = 1
incremental = false
opt-level = 3

[workspace.dependencies]
solana-program = "=2.1.0"
zeroize = "=1.7.0"
